# Generated by Django 4.1 on 2022-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
